-- MySQL Script generated by MySQL Workbench
-- Wed 04 Apr 2018 12:32:46 PM CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`sensortype`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`sensortype` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `radius` INT NOT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `mydb`.`sensor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`sensor` (
  `uuid` VARCHAR(36) NOT NULL,
  `mac_address` VARCHAR(45) NOT NULL,
  `sensor_type_id` INT NOT NULL,
  `longitude` FLOAT NOT NULL,
  `latitude` FLOAT NOT NULL,
  PRIMARY KEY (`uuid`),
  INDEX `sensor_type_idx` (`sensor_type_id` ASC),
  CONSTRAINT `sensor_type`
    FOREIGN KEY (`sensor_type_id`)
    REFERENCES `mydb`.`sensortype` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`measurement`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`measurement` (
  `uuid` VARCHAR(36) NOT NULL,
  `sensor_uuid` VARCHAR(36) NOT NULL,
  `value` FLOAT NOT NULL,
  `at` DATETIME NOT NULL,
  PRIMARY KEY (`uuid`),
  INDEX `sensor_idx` (`sensor_uuid` ASC),
  CONSTRAINT `sensor`
    FOREIGN KEY (`sensor_uuid`)
    REFERENCES `mydb`.`sensor` (`uuid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`sync_sensor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`sync_sensor` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `sensor_uuid` VARCHAR(36) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `sensor_idx` (`sensor_uuid` ASC),
  CONSTRAINT `sensor`
    FOREIGN KEY (`sensor_uuid`)
    REFERENCES `mydb`.`sensor` (`uuid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`sync_measurement`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`sync_measurement` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `measurement_uuid` VARCHAR(36) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `measurement_idx` (`measurement_uuid` ASC),
  CONSTRAINT `measurement`
    FOREIGN KEY (`measurement_uuid`)
    REFERENCES `mydb`.`measurement` (`uuid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
