-- MySQL Script generated by MySQL Workbench
-- do 05 apr 2018 15:32:23 CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema routingdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema routingdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `routingdb` DEFAULT CHARACTER SET utf8 ;
USE `routingdb` ;

-- -----------------------------------------------------
-- Table `routingdb`.`server`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `routingdb`.`server` (
  `id` INT NOT NULL,
  `database_name` VARCHAR(45) NOT NULL,
  `database_port` VARCHAR(4) NOT NULL DEFAULT '3306',
  `server_port` VARCHAR(4) NOT NULL DEFAULT '8081',
  `api_port` VARCHAR(4) NOT NULL DEFAULT '8080',
  `address` VARCHAR(45) NOT NULL,
  `pair_id` INT NULL,
  PRIMARY KEY (`id`));


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
